### ISSUE TITLE
[Core] Field Operations/Deep Dungeons Support

### ISSUE THREAD

**Issue by zbee** [PunishXIV/WrathCombo#97]
Explicit support for field operations is lacking, and will likely be a highly requested feature for the upcoming Dawntrail one.

At some point, some additions were made to the code to support older field operations, but this didn't end up going much of anywhere.
I want to identify where this feature is at, and what it may need.

- [ ] Deep Dungeon
  - [ ] Potions #773 (for the framework, it won't include DD potions)
  - [ ] Pomanders (?)

- [ ] Bozja
  - [x] Lost Actions (#171)
  - [x] Items & Essences (#171)
  - [x] Buffs/Debuffs pertaining to Lost Actions (#171)
  - [x] Un-holstering Lost Actions (4bd6647)
  - [ ] Refactor to be like OC

- [ ] Eureka
  - [ ] Logos Actions
  - [ ] Un-holstering Logos Actions 
  - [ ] Automatic Elemental setting?
  - [ ] Refactor to be like Occult Crescent's implementation

- [X] Generalize Occult Crescent's implementation #772
  - [X] Make the method a `TryGetAction` that saves the `out` to avoid running it twice
  - [X] Put it into `RunAnyFieldOpAction` or something, that runs OC, but also the refactored Bozja and Eureka

**Comment by edewen** [comment]
Im sure it would depend on how the field operation goes. if it is just something like giving a cure or shield thats one thing. But the full list of bozja lost actions is a whole lot to account for. 

We will have to see how the new content plays out

**Comment by zbee** [comment]
Certainly not the whole list, certainly not allowing many options; would only follow those recommended in the DSR rotations, I reckon.\
Still too early to know any design decisions ha.

**Comment by Kagekazu** [comment]
> [ ] Eureka
> * [ ]  Automatic Elemental setting?
 Isnt that base game? ->
![image](https://github.com/user-attachments/assets/a10779c2-2abf-449a-bfaa-e7884b247322)

**Comment by zbee** [comment]
@Taurenkey unassign this
